//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEN_PACIENTE
    {
        public int ID_EXAMEN_PACIENTE { get; set; }
        public int ID_EXAMEN { get; set; }
        public int ID_PACIENTE { get; set; }
        public System.DateTime FECHA_REALIZO { get; set; }
        public string ENCARGADO { get; set; }
    
        public virtual EXAMEN EXAMEN { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
