//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMEN()
        {
            this.EXAMEN_PACIENTE = new HashSet<EXAMEN_PACIENTE>();
        }
    
        public int ID_EXAMEN { get; set; }
        public string NOMBRE_EXAMEN { get; set; }
        public decimal PRECIO { get; set; }
        public string RECOMENDACION { get; set; }
        public string DESCRIPCION { get; set; }
        public string TRATAMIENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMEN_PACIENTE> EXAMEN_PACIENTE { get; set; }
    }
}
