//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int ID_TIPO_INVENTARIO { get; set; }
        public int ID_MEDICINA { get; set; }
        public int CANTIDAD { get; set; }
        public int ID_SUCURSAL { get; set; }
    
        public virtual MEDICINA MEDICINA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_INVENTARIO TIPO_INVENTARIO { get; set; }
    }
}
