//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_HABITACION
    {
        public int ID_PACIENTE_HABITACION { get; set; }
        public int ID_PACIENTE { get; set; }
        public int ID_HABITACION { get; set; }
        public System.DateTime Fecha_Estancia { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
